name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
        dependencies:
          - "lowest"
          - "highest"
        experimental:
          - false
    name: Tests with PHP ${{ matrix.php-version }} and ${{ matrix.dependencies }} dependencies

    steps:
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
      env:
        COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: npm install
    - name: Run ESLint
      run: npm run eslint -- eslint/rules Magento2 --ignore-pattern 'Magento2/Tests/Eslint/*Test.js'
    - name: Run JSCS
      run: npm run jscs eslint/rules Magento2

    - name: Validate composer
      run: composer validate

    - name: Composer install
      uses: "ramsey/composer-install@v1"
      with:
        dependency-versions: "${{ matrix.dependencies }}"
        composer-options: "${{ matrix.composer-options }}"

    - name: Run unit tests suite
      run: vendor/bin/phpunit

    - name: Run code style suite
      run: vendor/bin/phpcs --standard=Magento2 Magento2/Helpers/ Magento2/Sniffs
